# -*- yaml -*-
project:
  type: website
  title: "Population genomics in practice"
  output-dir: _site
  preview:
    port: 8888
  pre-render:
    - scripts/init-site.sh
    - scripts/setup-pgip-data.sh
    - scripts/setup-data.py
  render:
    - index.qmd
    # Slides
    - slides/index.qmd
    - slides/pgip/index.qmd
    - slides/foundations/index.qmd
    - slides/foundations/data.qmd
    - slides/variant_calling/index.qmd
    - slides/variant_calling/dna_sequencing.qmd
    - slides/variant_calling/read_mapping.qmd
    - slides/variant_calling/variant_calling.qmd
    - slides/variant_calling/reproducibility.qmd
    # - slides/variant_filtering/index.qmd
    # - slides/recombination/index.qmd
    # - slides/recombination/linkage.qmd
    # - slides/genetic_diversity/index.qmd
    # - slides/simulation/index.qmd
    # - slides/scratch/index.qmd
    # Exercises and datasets
    - exercises/index.qmd
    - exercises/compute_environment/index.qmd
    - exercises/datasets/monkeyflowers.qmd
    - exercises/variant_calling/index.qmd
    - exercises/variant_calling/introduction.qmd
    - exercises/variant_calling/data_qc.qmd
    - exercises/variant_calling/read_mapping.qmd
    - exercises/variant_calling/variant_calling_workflow.qmd
    # - exercises/variant_filtering/index.qmd
    # - exercises/variant_filtering/basic_filtering.qmd
    # - exercises/variant_filtering/advanced_filtering.qmd
    # - exercises/genetic_diversity/index.qmd
    # - exercises/genetic_diversity/landscape.qmd
    # - exercises/recombination_linkage/index.qmd
    # - exercises/recombination_linkage/ld_decay.qmd
    # - exercises/population_structure/index.qmd
    # - exercises/population_structure/pca.qmd
    # - exercises/population_structure/admixture.qmd
    # - exercises/population_structure/dstats.qmd
    # - exercises/demography/index.qmd
    # - exercises/selection/index.qmd
    # - exercises/simulation/index.qmd
    # - exercises/simulation/howto.qmd
    # - exercises/simulation/stdpopsim_lab.qmd
    # - exercises/simulation/stdpopsim_lab_II.qmd
    # - exercises/simulation/simulation.qmd
    # - exercises/ancestral_recombination_graphs/index.qmd
    # Recipes
    - recipes/index.qmd
    # - recipes/slides/index.qmd
    # - recipes/slim/index.qmd
    # # Exclude
    # - "!fixme.qmd"
    # - "*.ipynb"

metadata-files:
  - _website.yml

bibliography: assets/bibliography.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
lightbox: true

format:
  nbis-course-html:
    theme: [default, "assets/css/custom_html.scss"]
    toc: true
    embed-resources: false
    date: last-modified
    date-format: "DD-MMM-YYYY"
    code-link: true
    code-block-border-left: "#a7c947"
    page-layout: full
    fontsize: 1.4em
    lightbox:
      match: auto
  nbis-quarto-revealjs:
    footer: Population Genomics in Practice
    header-logo-left-url: https://nbis.se
    ultitle: true
    theme: ["assets/css/custom.scss"]
    smaller: true
    highlight-style: gruvbox
    fig-height: 12
    fig-width: 10
    fig-align: center
    fig-cap-location: bottom

execute:
  cache: true
  freeze: true
  echo: true
  warning: false
  include: true
  autodep: true
  eval: true
  error: false

filters:
  - quarto-ext/fontawesome
  - percyfal/nbis-course

knitr:
  opts_chunk:
    code-fold: false
    tidy: true
    comment-char: "#>"
    fig-format: svg
    engine.opts:
      dvisvgm.opts: --font-format=woff
      template: assets/www/tikzfig.tex
