[project]
authors = ["Per Unneberg <per.unneberg@scilifelab.se>"]
channels = ["conda-forge", "bioconda"]
description = "Population genomics in practice material"
name = "workshop-pgip-material"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"
requires-pixi = ">=0.45"

[tasks]
qpv = "pixi r -e build preview"
qrd = "pixi r -e build render"

[dependencies]
python = "3.11.*"

[feature.lint.dependencies]
pre-commit = ">=4.2.0,<5"
pre-commit-hooks = ">=5.0.0,<6"
shellcheck = ">=0.10.0,<0.11"
ruff = ">=0.11.11,<0.12"
typos = ">=1.32.0,<2"
actionlint = ">=1.7.7,<2"
go-shfmt = ">=3.11.0,<4"
prettier = ">=3.5.3,<4"
taplo = ">=0.9.3,<0.10"

[feature.lint.tasks]
actionlint = { cmd = "actionlint", env = { SHELLCHECK_OPTS = "-e SC2086" } }
lint = { cmd = "pre-commit run --all-files --hook-stage=manual", description = "Run all linters and formatters on all code" }
pre-commit-install = "pre-commit install --install-hooks -t=pre-commit -t=pre-push"
pre-commit-install-minimal = "pre-commit install -t=pre-commit"
pre-commit-run = "pre-commit run --all-files"
prettier-fmt = { cmd = "prettier --write" }
ruff-format = "ruff format --force-exclude"
ruff-lint = "ruff check --fix --exit-non-zero-on-fix --force-exclude"
shell-format = "shfmt --write --indent=4 --simplify --binary-next-line"
toml-format = { cmd = "taplo fmt", env = { RUST_LOG = "warn" } }
toml-lint = "taplo lint --verbose **/pixi.toml"
typecheck-python = "mypy"
typos = "typos --write-changes --force-exclude"

[feature.build.dependencies]
bedtools = ">=2.31.1,<3"
bioconductor-repitools = ">=1.52.0,<2"
jupyterlab = ">=4.4.2,<5"
jupyterlite = ">=0.5.1,<0.6"
pixy = ">=2.0.0.beta8,<3"
plink = ">=1.90b7.7,<2"
plink2 = ">=2.0.0a.6.9,<3"
qualimap = ">=2.3,<3"
r = ">=4.3,<4.5"
r-devtools = ">=2.4.5,<3"
r-expm = ">=1.0_0,<2"
r-gganimate = ">=1.0.8,<2"
r-ggraph = ">=2.1,<3"
r-gifski = ">=1.32.0_2,<2"
r-igraph = ">=2.0.3,<3"
r-latex2exp = ">=0.9.6,<0.10"
r-magrittr = ">=2.0.3,<3"
r-patchwork = ">=1.3.1,<2"
r-readr = ">=2.1.5,<3"
r-readxl = ">=1.4.5,<2"
r-tibble = ">=3.2.1,<4"
r-tidygraph = ">=1.3.0,<2"

[feature.build.tasks]
rpgip = "R -e \"library(devtools); devtools::install_local('src/R/pgip', upgrade=F)\""
preview = "quarto preview"
render = "quarto render"

[feature.ci.dependencies]
quarto = ">=1.7.31"

[feature.bioconductor.dependencies]
r-biocmanager = "*"
bioconductor-genomeinfodbdata = "*"
bioconductor-data-packages = "*"
bioconductor-biomart = "*"
r-ggplot2 = "*"

[environments]
lint = { features = ["lint"], solve-group = "prod" }
build = { features = ["build"], solve-group = "prod" }
ci = { features = ["build", "ci"], solve-group = "prod" }
bioconductor = { features = ["bioconductor"], solve-group = "prod" }
