[project]
authors = ["Per Unneberg <per.unneberg@scilifelab.se>"]
channels = ["conda-forge", "bioconda"]
description = "Population genomics in practice material"
name = "workshop-pgip-material"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"
requires-pixi = ">=0.45"

[tasks]

[dependencies]
python = "==3.11.9"

[feature.lint.dependencies]
pre-commit = ">=4.2.0,<5"
pre-commit-hooks = ">=5.0.0,<6"
shellcheck = ">=0.10.0,<0.11"
ruff = ">=0.11.11,<0.12"
typos = ">=1.32.0,<2"
actionlint = ">=1.7.7,<2"
go-shfmt = ">=3.11.0,<4"
prettier = ">=3.5.3,<4"
taplo = ">=0.9.3,<0.10"

[feature.lint.tasks]
actionlint = { cmd = "actionlint", env = { SHELLCHECK_OPTS = "-e SC2086" } }
lintall = { cmd = "pre-commit run --all-files --hook-stage=manual", description = "Run all linters and formatters on all code" }
lint = { cmd = "pre-commit run --hook-stage=manual", description = "Run all linters and formatters on staged code" }
pre-commit-install = "pre-commit install --install-hooks -t=pre-commit -t=pre-push"
pre-commit-install-minimal = "pre-commit install -t=pre-commit"
pre-commit-run = "pre-commit run --all-files"
prettier-fmt = { cmd = "prettier --write" }
ruff-format = "ruff format --force-exclude"
ruff-lint = "ruff check --fix --exit-non-zero-on-fix --force-exclude"
shell-format = "shfmt --write --indent=4 --simplify --binary-next-line"
toml-format = { cmd = "taplo fmt", env = { RUST_LOG = "warn" } }
toml-lint = "taplo lint --verbose **/pixi.toml"
typecheck-python = "mypy"
typos = "typos --write-changes --force-exclude"

[feature.build.dependencies]
"r-data.table" = ">=1.17.8,<2"
"r-data.tree" = ">=1.2.0,<2"
admixtools = ">=8.0.2,<9"
admixture = ">=1.3.0,<2"
bcftools = ">=1.22,<2"
bedtools = ">=2.31.1,<3"
bioconductor-repitools = ">=1.52.0,<2"
bokeh = ">=3.5.0,<3.6.0"
bwa = ">=0.7.19,<0.8"
conda = ">=25.7.0,<26"
csvtk = ">=0.34.0,<0.35"
dask = "==2024.8.1"
demesdraw = ">=0.4.0,<0.5"
fastqc = ">=0.12.1,<0.13"
gatk4 = ">=4.6.2.0,<5"
graphviz = ">=12.2.1,<13"
jupyter-cache = ">=1.0.1,<2"
jupyter_console = ">=6.6.3,<7"
jupyterlab = ">=4.4.2,<5"
jupyterlite = ">=0.5.1,<0.6"
jupyterquiz = ">=2.9.6.2,<3"
jupytext = ">=1.17.3,<2"
mosdepth = ">=0.3.11,<0.4"
msprime = ">=1.3.4,<2"
multiqc = ">=1.30,<2"
picard = ">=3.4.0,<4"
plink = ">=1.90b7.7,<2"
plink2 = ">=2.0.0a.6.9,<3"
qualimap = ">=2.3,<3"
quarto = ">=1.7.33,<2"
r = ">=4.3,<4.5"
r-ape = ">=5.8_1,<6"
r-blogdown = ">=1.21,<2"
r-cubelyr = ">=1.0.2,<2"
r-devtools = ">=2.4.5,<3"
r-doparallel = ">=1.0.17,<2"
r-expm = ">=1.0_0,<2"
r-furrr = ">=0.3.1,<0.4"
r-gganimate = ">=1.0.8,<2"
r-ggraph = ">=2.1,<3"
r-ggrepel = ">=0.9.6,<0.10"
r-gifski = ">=1.32.0_2,<2"
r-gsalib = ">=2.2.1,<3"
r-here = ">=1.0.1,<2"
r-igraph = ">=2.0.3,<3"
r-kableextra = ">=1.4.0,<2"
r-latex2exp = ">=0.9.6,<0.10"
r-lobstr = ">=1.1.2,<2"
r-magrittr = ">=2.0.3,<3"
r-pak = ">=0.9.0,<0.10"
r-patchwork = ">=1.3.1,<2"
r-plotly = ">=4.11.0,<5"
r-quadprog = ">=1.5_8,<2"
r-readr = ">=2.1.5,<3"
r-readxl = ">=1.4.5,<2"
r-reticulate = ">=1.43.0,<2"
r-tibble = ">=3.2.1,<4"
r-tidygraph = ">=1.3.0,<2"
r-tidyverse = ">=2.0.0,<3"
r-usethis = ">=3.2.1,<4"
samtools = ">=1.22.1,<2"
seqkit = ">=2.10.1,<3"
slim = ">=5.0,<6"
snakemake = ">=9.9.0,<10"
stdpopsim = ">=0.3.0,<0.4"
tskit = ">=0.6.4,<0.7"
vcflib = ">=1.0.12,<2"
vcftools = ">=0.1.17,<0.2"
zarr = "<3"
pixy = ">=2.0.0.beta12,<3"
xyzservices = "==2024.6.0"

[feature.build.tasks]
rpgip = "R -e \"library(devtools); devtools::install_local('src/R/pgip', upgrade=F)\""
radmixr = "R -e \"library(devtools); devtools::install_github('bodkan/admixr', upgrade=F)\""
radmixtools2 = "R -e \"library(devtools); devtools::install_github('uqrmaie1/admixtools', upgrade=F)\""
rsetup = { depends-on = ["rpgip", "radmixtools2"] }

[feature.build.tasks.jlab]
args = [{ "arg" = "port", default = "8899" }]
cmd = "jupyter lab --port {{port}}"
description = "Run Jupyter lab."

[feature.build.tasks.pv]
args = [{ "arg" = "port", default = "8889" }]
cmd = "quarto preview --port {{port}}"

[feature.build.tasks.rd]
cmd = "quarto render"

[feature.build.tasks.prod]
cmd = "quarto render --profile production"

[feature.build.pypi-dependencies]
tseda = { git = "https://github.com/percyfal/tseda.git", rev = "pgip" }

[feature.bioconductor.dependencies]
r-biocmanager = "*"
bioconductor-genomeinfodbdata = "*"
bioconductor-data-packages = "*"
bioconductor-biomart = "*"
r-ggplot2 = "*"

[environments]
lint = { features = ["lint"], solve-group = "prod" }
build = { features = ["build"], solve-group = "prod" }
bioconductor = { features = ["bioconductor"], solve-group = "prod" }
