---
title: Exercises
subtitle: "PGIP 2025 • Population Genomics in Practice"
description: List of all exercises
format:
  nbis-course-html:
    number-sections: false
listing:
  id: exercise-listings
  type: grid
  grid-columns: 4
  fields: [title, subtitle, author]
  sort: false
  contents:
    - compute_environment/index.qmd
    - datasets/monkeyflowers.qmd
    - variant_calling/index.qmd
    - variant_filtering/index.qmd
    - genetic_diversity/index.qmd
    - recombination_linkage/index.qmd
    - population_structure/index.qmd
    - demography/index.qmd
    - selection/index.qmd
    - simulation/index.qmd
    - ancestral_recombination_graphs/index.qmd
toc: false
sidebar: false
execute:
  freeze: false
---

## Information

All exercise pages start with a callout block that provides
information on how to setup the relevant [Compute
environment](compute_environment/index.qmd). The callout blocks are
labelled with icons that indicate the type of environment ({{< fa
server >}} PDC resource; {{< fa laptop >}} local compute environment;
{{< fa brands firefox >}} online browser-based resource). Make sure to
read these instructions before proceeding with the exercise itself.
Some of the documents include a link to an external URL that hosts the
actual exercise instructions.

## On self-assessment exercise blocks

Scattered throughout the documents are exercise blocks, with hidden
answers, and, in some cases, hints. The exercises are for
self-assessment of your understanding, but they are not mandatory.

Some of the exercises (labelled with the Linux penguin {{< fa brands
linux >}}) are related to the usage of the command line interfaces
(CLI), and how to obtain information about what a program does. This
is an essential skill when working in Linux/UNIX environments! These
exercises can be skipped if you are an experienced Linux/UNIX user.

An example exercise is provided here:

::: {.callout-exercise}

### Example exercise block

{{< fa brands linux >}} The `ls` command is used to list the contents
of a directory. What option provides a so-called long listing format?

::: {.callout-hint}

Type `ls --help` to show the options to `ls`.

:::

::: {.callout-answer}

The `-l` option uses the long listing format, i.e., the command to use
is `ls -l`.

:::

:::

## Exercises
