# -*- yaml -*-
name: CI

on:
  push:
    branches:
      - main
      - test-build
    tags:
      - "v*"
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  XDG_CACHE_HOME: ${{ github.workspace }}/.cache
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.54.2
          cache: true
          environments: lint

      - name: pre-commit
        run: pixi run pre-commit-run --color=always --show-diff-on-failure

  build:
    name: Build site
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      - name: Cancel Previous Runs
        if: ${{ !env.ACT }}
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.54.2
          environments: build
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          activate-environment: true

      - name: Install TeXLive
        run: |
          sudo apt-get update
          sudo apt-get install texlive texlive-latex-extra

      - name: Add rpgip package and admixtools2
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: pixi run rsetup

      - run: echo "TEXINPUTS=$TEXINPUTS:$GITHUB_WORKSPACE/src/latex" >> $GITHUB_ENV
      - run: echo "RETICULATE_PYTHON=${GITHUB_WORKSPACE}/.pixi/envs/build/bin/python" >> $GITHUB_ENV
      - run: echo "QUARTO_PYTHON=${GITHUB_WORKSPACE}/.pixi/envs/build/bin/python" >> $GITHUB_ENV
      - run: R -e "library(reticulate); reticulate::py_config()"
      - run: echo "QUARTO_PYTHON ${QUARTO_PYTHON}"
      - run: echo "RETICULATE_PYTHON ${RETICULATE_PYTHON}"
      - run: which python
      - run: echo "PIXI_ENVIRONMENT_NAME ${PIXI_ENVIRONMENT_NAME}"

      - name: Render project without publishing
        env:
          QUARTO_PRINT_STACK: true
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          quarto render .
          echo "QUARTO_OUTPUT=_site" >> $GITHUB_ENV

      - name: Publish to GitHub Pages
        env:
          GITHUB_EMAIL: quarto-github-actions-publish@example.com
          GITHUB_USERNAME: gh_action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUARTO_PRINT_STACK: true
        if: ${{ github.ref_name == 'main' || github.ref_name == 'test-build' }}
        run: |
          git config --global user.email "${{ env.GITHUB_EMAIL }}"
          git config --global user.name "${{ env.GITHUB_USERNAME }}"
          quarto publish gh-pages --no-browser
