# -*- yaml -*-
name: CI

on:
  push:
    branches:
      - main
      - test-build
    tags:
      - "v*"
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  XDG_CACHE_HOME: ${{ github.workspace }}/.cache
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          environments: lint

      - name: pre-commit
        run: pixi run pre-commit-run --color=always --show-diff-on-failure

  build:
    name: Build site
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Cancel Previous Runs
        if: ${{ !env.ACT }}
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          environments: ci
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Add rpgip package and admixtools2
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pixi run -e ci rsetup

      - name: Render project without publishing
        env:
          QUARTO_PRINT_STACK: true
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "TEXINPUTS=$TEXINPUTS:$GITHUB_WORKSPACE/src/latex" >> $GITHUB_ENV
          quarto render .
          echo "QUARTO_OUTPUT=_site" >> $GITHUB_ENV
        shell: pixi run -e ci bash -e {0}

      - name: Publish to GitHub Pages
        env:
          GITHUB_EMAIL: quarto-github-actions-publish@example.com
          GITHUB_USERNAME: gh_action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUARTO_PRINT_STACK: true
        if: ${{ github.ref_name == 'main' || github.ref_name == 'test-build' }}
        run: |
          git config --global user.email "${{ env.GITHUB_EMAIL }}"
          git config --global user.name "${{ env.GITHUB_USERNAME }}"
          quarto publish gh-pages --no-browser
        shell: pixi run -e ci bash -e {0}
